name: Production CI/CD

on:
  push:
    branches: [ main ]

jobs:
  deploy-to-production:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        pip install --upgrade pip
        pip install -r backend/requirements.txt
        pip install dvc[all]

    - name: DVC Pull
      run: dvc pull
      env:
        GIT_USER: ${{ secrets.GIT_USER }}
        GIT_TOKEN: ${{ secrets.GIT_TOKEN }}

    - name: Run tests
      run: |
        python -m py_compile backend/app/*.py

    - name: Build Docker image
      run: |
        docker build -f backend/Dockerfile -t house-prediction .

    - name: Log in to DockerHub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Tag image for DockerHub
      run: |
        docker tag house-prediction ${{ secrets.DOCKERHUB_USERNAME }}/house-prediction:latest

    - name: Push image to DockerHub
      run: |
        docker push ${{ secrets.DOCKERHUB_USERNAME }}/house-prediction:latest
