name: Staging CI/CD

on:
  push:
    branches: [ staging ]

jobs:
  test-and-deploy-staging:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        pip install --upgrade pip
        pip install -r backend/requirements.txt
        pip install dvc[all]

    - name: DVC Pull
      run: dvc pull
      env:
        GIT_USER: ${{ secrets.GIT_USER }}
        GIT_TOKEN: ${{ secrets.GIT_TOKEN }}

    - name: Run all tests
      run: |
        python -m py_compile backend/app/*.py

    - name: Build Docker image
      run: |
        docker build -f backend/Dockerfile -t house-price-backend .
