name: Staging CI/CD

on:
  push:
    branches: [ staging ]

jobs:
  test-and-deploy-staging:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0  # Important pour avoir tout l'historique

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        pip install --upgrade pip
        pip install -r backend/requirements.txt
        pip install pytest
        pip install dvc[all]

    - name: DVC Pull
      run: dvc pull
      env:
        GIT_USER: ${{ secrets.GIT_USER }}
        GIT_TOKEN: ${{ secrets.GIT_TOKEN }}

    - name: Run all tests
      run: |
        # Syntax check
        python -m py_compile backend/app/*.py
        # Run ALL tests
        python -m pytest backend/tests

    - name: Build Docker image
      run: |
        docker build -f backend/Dockerfile -t house-price-backend .

    - name: Promote to production
      run: |
        git config user.name "ci-bot"
        git config user.email "ci-bot@example.com"
        git fetch origin
        git checkout main
        git merge staging --no-ff -m "CI: Promote staging to main [skip ci]"
        git push origin main
